-- 시퀀스
CREATE SEQUENCE userNumber_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOOKNUMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NOTICENUM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BORROWNUMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqPostID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqRoomID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqMessageID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TRADE_CHATROOM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRADE_CHATMESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seqFavoriteID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seqTransactionID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE activity_log_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATA SEQUENCE NOTIFICATIONS_SEQ START 1 WITH INCREMENT BY 1;
CREATA SEQUENCE BORROWRECORD_SEQ START 1 WITH INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HELPFUL_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 인덱스 추가
CREATE INDEX IDX_CHATROOM_SELLER ON TRADE_CHATROOM(SELLERNUMBER);
CREATE INDEX IDX_CHATROOM_BUYER ON TRADE_CHATROOM(BUYERNUMBER);
CREATE INDEX IDX_CHATROOM_POST ON TRADE_CHATROOM(POSTID);
CREATE INDEX IDX_CHATMESSAGE_ROOM ON TRADE_CHATMESSAGE(ROOMID);
CREATE INDEX IDX_CHATMESSAGE_SENDER ON TRADE_CHATMESSAGE(SENDERNUMBER);
CREATE INDEX IDX_CHATMESSAGE_CREATEDAT ON TRADE_CHATMESSAGE(CREATEDAT);
CREATE INDEX idx_activity_type ON ACTIVITY_LOG(activity_type);
CREATE INDEX idx_actor_type ON ACTIVITY_LOG(actor_type);
CREATE INDEX idx_log_date ON ACTIVITY_LOG(log_date);
CREATE INDEX IDX_NOTI_USER ON NOTIFICATIONS(USER_NUMBER);
CREATE INDEX IDX_NOTI_SENT ON NOTIFICATIONS(SENT);
CREATE INDEX IDX_NOTI_READ ON NOTIFICATIONS(READ);

-- 세션 어쩌구
ALTER SESSION SET PLSCOPE_SETTINGS='IDENTIFIERS:NONE';